ENV['COCOAPODS_DISABLE_STATS'] = "true"

platform :osx, '10.12'

target 'Savitar2' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Savitar2
#  pod 'BlueSocket'

  target 'Savitar2Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Savitar2UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
