#!/usr/bin/env bash
# Generate Sparkle appcast files and open a PR on master (branch protection safe).
set -euo pipefail

input="${1:?Usage: publish-sparkle-appcast.sh TAG (e.g. v2.0.18 or 2.0.18)}"
version="${input#v}"
tag="v${version}"
if [[ ! "$version" =~ ^[0-9]+(\.[0-9]+)*([A-Za-z0-9._-]+)?$ ]]; then
  echo "::error::Invalid release tag '${input}'. Expected v2.0.18 or 2.0.18."
  exit 1
fi
repo_root="$(cd "$(dirname "$0")/../.." && pwd)"
cd "$repo_root"

if [ -z "${SPARKLE_EDDSA_PRIVATE_KEY:-}" ]; then
  echo "::error::SPARKLE_EDDSA_PRIVATE_KEY is not set."
  exit 1
fi

zip_path="client/fastlane/release/Savitar.zip"
if [ ! -f "$zip_path" ]; then
  echo "Downloading ${tag} release artifact…"
  mkdir -p client/fastlane/release
  gh release download "$tag" --pattern 'Savitar.zip' --dir client/fastlane/release
fi

updates_dir="client/appcast/updates"
key_file="${RUNNER_TEMP:-/tmp}/sparkle-ed25519.key"
mkdir -p "$updates_dir"
cp "$zip_path" "$updates_dir/Savitar.zip"

if [ -f CHANGELOG.md ]; then
  awk -v ver="$version" '
    $0 ~ "^## \\[" ver "\\]" { capture = 1; next }
    capture && /^## \[/ { exit }
    capture { print }
  ' CHANGELOG.md | awk 'NF { seen = 1 } seen' > "$updates_dir/Savitar.md" || true
fi

if [ ! -s "$updates_dir/Savitar.md" ]; then
  gh release view "$tag" --json body --jq '.body' > "$updates_dir/Savitar.md" || true
fi

printf '%s' "$SPARKLE_EDDSA_PRIVATE_KEY" > "$key_file"
cd client
xcodebuild -resolvePackageDependencies \
  -project Savitar2.xcodeproj -scheme Savitar2 \
  -derivedDataPath build/sparkle-tools -quiet
generate_appcast="build/sparkle-tools/SourcePackages/artifacts/sparkle/Sparkle/bin/generate_appcast"
"$generate_appcast" \
  --ed-key-file "$key_file" \
  --download-url-prefix "https://github.com/jkoutavas/Savitar2/releases/download/${tag}/" \
  appcast/updates
rm -f "$key_file"
mv appcast/updates/appcast.xml appcast/appcast.xml
cp appcast/updates/*.md appcast/ 2>/dev/null || true
ruby <<'RUBY'
appcast = "appcast/appcast.xml"
url = "https://github.com/jkoutavas/Savitar2/blob/master/CHANGELOG.md"
text = File.read(appcast)
link = "            <sparkle:fullReleaseNotesLink>#{url}</sparkle:fullReleaseNotesLink>"
text = if text.include?("fullReleaseNotesLink")
  text.gsub(/<sparkle:fullReleaseNotesLink>[^<]*<\/sparkle:fullReleaseNotesLink>/, link.strip)
else
  text.gsub(
    /(<sparkle:releaseNotesLink>[^<]*<\/sparkle:releaseNotesLink>)/,
    "\\1\n#{link}"
  )
end
File.write(appcast, text)
RUBY
cd "$repo_root"

git config user.name "github-actions[bot]"
git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
git fetch origin master
git checkout master
git pull --ff-only origin master

branch="release/appcast-${tag}"
if git show-ref --verify --quiet "refs/heads/${branch}"; then
  git branch -D "$branch"
fi
git checkout -b "$branch"

git add client/appcast/appcast.xml client/appcast/*.md
if git diff --staged --quiet; then
  echo "Appcast unchanged; nothing to publish."
  exit 0
fi

git commit -m "Update Sparkle appcast for ${tag}"
git push -u origin "$branch" --force

existing_pr="$(gh pr list --head "$branch" --state open --json url --jq '.[0].url' || true)"
if [ -n "$existing_pr" ]; then
  echo "Appcast PR already open: ${existing_pr}"
  exit 0
fi

pr_url="$(gh pr create \
  --base master \
  --head "$branch" \
  --title "Update Sparkle appcast for ${tag}" \
  --body "Automated Sparkle appcast update for **${tag}**.

Merge this PR to publish the update feed at \`client/appcast/appcast.xml\` (Sparkle checks \`master\`).

Generated by the release workflow run: ${GITHUB_SERVER_URL:-https://github.com}/${GITHUB_REPOSITORY:-jkoutavas/Savitar2}/actions/runs/${GITHUB_RUN_ID:-manual}")"

echo "Opened appcast PR: ${pr_url}"
